spring.application.name=Task Manager

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=postgres

api.jwt.token.secret=my-secret-key
api.jwt.token.issuer=everton